// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"time"
)

type Dynamic struct {
	ID         int32     `json:"id"`
	LichessID  string    `json:"lichess_id"`
	Username   string    `json:"username"`
	Rapid      int32     `json:"rapid"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}

type Static struct {
	ID        int32     `json:"id"`
	LichessID string    `json:"lichess_id"`
	Username  string    `json:"username"`
	Rapid     int32     `json:"rapid"`
	CreatedAt time.Time `json:"created_at"`
}
