// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"context"
)

type Querier interface {
	CheckEntriesDynamic(ctx context.Context) (int64, error)
	CheckEntriesStatic(ctx context.Context) (int64, error)
	GetallDynamic(ctx context.Context) ([]GetallDynamicRow, error)
	GetallStatic(ctx context.Context) ([]GetallStaticRow, error)
	InsertDynamic(ctx context.Context, arg InsertDynamicParams) error
	InsertStatic(ctx context.Context, arg InsertStaticParams) error
	UpdateDynamic(ctx context.Context, arg UpdateDynamicParams) error
}

var _ Querier = (*Queries)(nil)
